### ISSUE TITLE
SSL defaults to "false", which is not a valid value.

### ISSUE THREAD

**Issue by macprog-guy** [urbica/pg-migrate#157]
Hello,

I think that because the -ssl option is not a flag but an option, docopt generates the string value 'false' when it's not present. 
This is not a legal value for that option (need conversion to a boolean). Furthermore, because the string 'false' is truthy,
we can't provide the option via environment variables.

```javascript
...
// Environment variables never get used because opt is the string "false" 
ssl: opt['--ssl'] || process.env.PGSSL || process.env.POSTGRES_SSL
...
```

Thanks for the otherwise nice library.

**Comment by stepankuzmin** [comment]
Thanks for the issue! tThis should be fixed in v1.2.1
